services:
  - type: web
    name: conversor-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && pip install pandoc
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT